vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|18 Sep 2025 12:07:07 -0000
vti_extenderversion:SR|6.0.2.8161
vti_backlinkinfo:VX|myaccount/acts/acts_db.asp myaccount/signup.asp myaccount/dancers/dancer_new.asp myaccount/acts/archive/acts_edit_copy(1).asp myaccount/dancers/allocation_lists.asp myaccount/dancers/archive/add2db.asp
vti_syncofs_2.59.119.221\:21:TW|18 Sep 2025 14:31:00 -0000
vti_syncwith_2.59.119.221\:21:TW|18 Sep 2025 12:07:07 -0000
vti_author:SR|SAF-ACER\\safen
vti_modifiedby:SR|SAF-ACER\\safen
vti_timecreated:TR|18 Sep 2025 12:07:07 -0000
