<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>New Page 1</title>
</head>

<body>

<div align="center">
	<table border="0" style="border-collapse: collapse" width="90%">
		<tr>
			<td>
			<table width="100%" border="1" style="color: #FFFFFF; font-family: serif; font-size: 10pt">
				<thead>
				</thead>
				<tbody>
					<!--webbot bot="DatabaseRegionStart" s-columnnames="filler,invoice_notes,company_number,invoice_address,company_name,deposit_wod,discount_wod,deposit_tr,discount_tr,deposit_lv,discount_lv,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,city,mobile,email,surname,fname,contact,studioname,studio_ID" s-columntypes="130,203,202,203,202,6,6,6,6,6,6,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,202,202,3" s-dataconnection="s4d_2025" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns s-criteria s-order s-sql="update studios set contact='::contact::'&lt;br&gt;where studio_ID=::studio_ID::" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields="contact=&amp;amp;studio_ID=" s-norecordsfound="Contact Name Updated" i-maxrecords="1" i-groupsize="0" botid="0" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="TRUE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="update studios set contact='::contact::' where studio_ID=::studio_ID::"
fp_sDefault="contact=&studio_ID="
fp_sNoRecords="<tr><td colspan=16 align=""LEFT"" width=""100%"">Contact Name Updated</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&filler=130&invoice_notes=203&company_number=202&invoice_address=203&company_name=202&deposit_wod=6&discount_wod=6&deposit_tr=6&discount_tr=6&deposit_lv=6&discount_lv=6&bulk_uploaded=11&bulk_link=201&duplicates=202&secureno=20&sessionID=20&ipaddress=202&lastupdated=135&datecreated=135&pincode=3&instagram=202&countryID=3&city=202&mobile=202&email=202&surname=202&fname=202&contact=202&studioname=202&studio_ID=3&"
fp_iDisplayCols=16
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
			</table>
			</td>
		</tr>
	</table>
</div>

</body>

</html>
