<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Europestage || we love dancing</title>

<link rel="stylesheet" type="text/css" href="styles.css">

</head>

<body style="background-color: #152D24">

<div align="center">
	<table border="0" style="border-collapse: collapse" class="spots-number" width=70px>
		<tr>
			<td>
			<table width="100%">
				<tbody>
					<!--webbot bot="DatabaseRegionStart" s-columnnames="total" 
     s-columntypes="3" s-dataconnection="s4d_2025" 
     b-tableformat="TRUE" b-menuformat="FALSE" 
     s-menuchoice="total" s-menuvalue="total" 
     b-tableborder="FALSE" b-tableexpand="TRUE" 
     b-tableheader="FALSE" b-listlabels="TRUE" 
     b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" 
     s-recordsource s-displaycolumns="total" s-criteria s-order 
     s-sql="SELECT 180-count(act_ID) as total from acts where eventID=9" 
     b-procedure="FALSE" clientside suggestedext="asp" 
     s-defaultfields s-norecordsfound="No records returned." 
     i-maxrecords="0" i-groupsize="0" botid="0" 
     u-dblib="_fpclass/fpdblib.inc" 
     u-dbrgn1="_fpclass/fpdbrgn1.inc" 
     u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" 
     preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
     b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
     b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" 
     sa-CritTypes b-WasTableFormat="TRUE" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT 180-count(act_ID) as total from acts where eventID=9"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=1 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="total"
fp_sMenuValue="total"
fp_sColTypes="&total=3&"
fp_iDisplayCols=1
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
						<td class="spots-number" 
      style="background-color: #152D24">
						<font color="#15FFA5">
						<!--webbot bot="DatabaseResultColumn" 
      s-columnnames="total" s-column="total" 
      b-tableformat="TRUE" b-hashtml="FALSE" 
      b-makelink="FALSE" clientside b-MenuFormat 
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
      s-ColumnTypes="3" startspan --><%=FP_FieldVal(fp_rs,"total")%><!--webbot 
      bot="DatabaseResultColumn" endspan --></font></td>
					</tr>
					<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" 
     b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" 
     i-groupsize="0" clientside tag="TBODY" 
     preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
     startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
			</table>
			</td>
		</tr>
	</table>
</div>
<p>&nbsp;</p>
<p align="center">&nbsp;</p>

</body>

</html>
