<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<script src="https://kit.fontawesome.com/e9d2b8eb05.js" crossorigin="anonymous"></script>
<title>Europestage || we love dancing</title>
<style>
input[type="checkbox"].unselectable {
pointer-events: none; /* Disables pointer interactions */
opacity: 0.6; /* Optional: visually indicate it's disabled */
}
</style>
<link rel="stylesheet" type="text/css" href="../simple.css">
<base target="_blank">
</head>

<body link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF">

<div align="center">
	<table width="100%" class="div2" style="color: #FFFFFF; border-bottom-width:0px; width:340px">
			<tr>
				<th ALIGN="LEFT">Sound = <i class="fa-duotone fa-regular fa-music fa-lg" style="--fa-primary-color: #72a1fd; --fa-secondary-color: #72a1fd;"></i>
				&nbsp;&nbsp;&nbsp;</th>
			</tr>
	</table>
	<table class="div2">
		<tbody>
			<!--webbot bot="DatabaseRegionStart" 
   s-columnnames="studioname,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,city,mobile,email,surname,fname,contact,studio_ID" 
   s-columntypes="202,130,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,202,3" 
   s-dataconnection="s4d_2025" b-tableformat="TRUE" 
   b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="FALSE" 
   b-tableexpand="FALSE" b-tableheader="FALSE" b-listlabels="TRUE" 
   b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" 
   s-recordsource s-displaycolumns="studioname" s-criteria s-order 
   s-sql="SELECT studioname FROM studios&lt;br&gt;where studio_ID=::studioID0::" 
   b-procedure="FALSE" clientside suggestedext="asp" 
   s-defaultfields="studioID0=0" s-norecordsfound i-maxrecords="1" 
   i-groupsize="0" botid="3" u-dblib="../../_fpclass/fpdblib.inc" 
   u-dbrgn1="../../_fpclass/fpdbrgn1.inc" 
   u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   startspan --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT studioname FROM studios where studio_ID=::studioID0::"
fp_sDefault="studioID0=0"
fp_sNoRecords="<tr><td colspan=1 align=""LEFT"" width=""100%""></td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&studioname=202&filler=130&bulk_uploaded=11&bulk_link=201&duplicates=202&secureno=20&sessionID=20&ipaddress=202&lastupdated=135&datecreated=135&pincode=3&instagram=202&countryID=3&city=202&mobile=202&email=202&surname=202&fname=202&contact=202&studio_ID=3&"
fp_iDisplayCols=1
fp_fCustomQuery=True
BOTID=3
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
				<td>
				<p align="center"><font face="Bahnschrift" color="#FF7B00">
				<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="studioname,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,city,mobile,email,surname,fname,contact,studio_ID" 
    s-column="studioname" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;studioname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"studioname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --> ~ MY ACTS 
				REGISTERED FOR</font></td>
			</tr>
			<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" 
   b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" 
   i-groupsize="0" clientside tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
	</table>
</div>
<div align="center">

	<table width="100%" class="div2" style="color: #FFFFFF; width:340px">
		<thead>
			<tr>
				<th ALIGN="LEFT" width="100%" colspan="2">&nbsp;</th>
			</tr>
			<tr>
				<th ALIGN="LEFT" width="100%" colspan="2">
				<font color="#FF7B00" size="3">
				WOD LATVIA</font></th>
			</tr>
			<tr>
				<th ALIGN="LEFT" style="border-bottom-style: solid; border-bottom-width: 1px" colspan="2">act 
				/ team / <font color="#99CCFF">details</font></th>
			</tr>
		</thead>
		<tbody>
			<!--webbot bot="DatabaseRegionStart" 
   s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
   s-columntypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130" 
   s-dataconnection="s4d_2025" b-tableformat="TRUE" 
   b-menuformat="FALSE" s-menuchoice="act_ID" s-menuvalue="act_ID" 
   b-tableborder="FALSE" b-tableexpand="TRUE" b-tableheader="TRUE" 
   b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" 
   b-makeform="FALSE" s-recordsource 
   s-displaycolumns="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
   s-criteria s-order 
   s-sql="SELECT * FROM acts where studioID = ::studioID0::&lt;br&gt;and eventID=9&lt;br&gt;order by actname ASC" 
   b-procedure="FALSE" clientside suggestedext="asp" 
   s-defaultfields="studioID0=0" 
   s-norecordsfound="No Acts declared for WOD Latvia" i-maxrecords="0" 
   i-groupsize="0" botid="5" u-dblib="../../_fpclass/fpdblib.inc" 
   u-dbrgn1="../../_fpclass/fpdbrgn1.inc" 
   u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
   b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes 
   b-WasTableFormat="TRUE" startspan b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM acts where studioID = ::studioID0:: and eventID=9 order by actname ASC"
fp_sDefault="studioID0=0"
fp_sNoRecords="<tr><td colspan=27 align=""LEFT"" width=""100%"">No Acts declared for WOD Latvia</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="act_ID"
fp_sMenuValue="act_ID"
fp_sColTypes="&act_ID=3&eventID=3&eventname=202&studioID=3&teamname=202&choreographer=202&actname=202&act_format=130&act_type=3&comp_numbers=3&act_nomination=202&act_agegroup=130&act_division=130&act_min_age=3&act_max_age=3&act_duration=130&mixed=11&mixedage=130&music_on_entry=202&notes=203&sound_link=201&background_link=201&combined=11&datecreated=135&lastupdated=135&duplicates=202&filler=130&"
fp_iDisplayCols=27
fp_fCustomQuery=True
BOTID=5
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
				<td width="100%" style="border-bottom-style: none; border-bottom-width: medium" colspan="2"><font color="#FFFFFF">
				<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
    s-column="actname" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;actname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"actname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --> /
				<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
    s-column="teamname" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;teamname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"teamname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --> / </font>
				<font color="#99CCFF">
				<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
    s-column="act_format" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_format&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"act_format")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
    s-column="act_nomination" b-tableformat="TRUE" 
    b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_nomination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"act_nomination")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font></td>
			</tr>
			<tr>
				<td width="34%" style="border-top-style: none; border-top-width: medium; border-bottom-style: solid; border-bottom-width: 1px" align="left" height="50">
				<p style="margin-top: 6px; margin-bottom: 6px">
				<font color="#99CCFF">
				<!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler" 
    s-column="act_agegroup" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_agegroup&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"act_agegroup")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font face="Bahnschrift">&nbsp;&nbsp;
				</font></td>
				<td width="66%" style="border-top-style: none; border-top-width: medium; border-bottom-style: solid; border-bottom-width: 1px" align="center" height="50">
				<a href="<%=FP_FieldVal(fp_rs,"sound_link")%>" target="_blank"><i class="fa-duotone fa-regular fa-music fa-xl" style="--fa-primary-color: #72a1fd; --fa-secondary-color: #72a1fd;"></i></a></td>
			</tr>
			<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" 
   b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" 
   i-groupsize="0" clientside tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
	</table>
</div>

</body>

</html>
