<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Europestage || we love dancing</title>
<script src="https://kit.fontawesome.com/247c7fd0d8.js" crossorigin="anonymous"></script>
</head>

<body>

<div align="center">
	<table border="0" style="border-collapse: collapse">
		<tr>
			<td align="center">

			<td align="center">
			<img border="0" src="../studios/green-tick.png"></td>
			<td align="left">
			<div align="center">
				<table width="100%" 
    style="color: #FFFFFF; font-family: Bahnschrift; font-size: 10pt">
					<tbody>
						<!--webbot bot="DatabaseRegionStart" 
      s-columnnames="eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,block1,riga_acts,event1,studioID,reserveID" 
      s-columntypes="130,135,6,135,3,3,3,3,6,135,3,3,3,3,6,135,3,3,3,3,3,3,3" 
      s-dataconnection="s4d_2025" b-tableformat="TRUE" 
      b-menuformat="FALSE" s-menuchoice s-menuvalue 
      b-tableborder="FALSE" b-tableexpand="TRUE" 
      b-tableheader="FALSE" b-listlabels="TRUE" 
      b-listseparator="TRUE" i-listformat="0" 
      b-makeform="FALSE" s-recordsource s-displaycolumns 
      s-criteria s-order 
      s-sql="update reserved_places set riga_acts=::riga_acts:: , block1=::block1:: , lastupdated=getDate() &lt;br&gt;where studioID=::studioID0::" 
      b-procedure="FALSE" clientside suggestedext="asp" 
      s-defaultfields="riga_acts=&amp;amp;block1=&amp;amp;studioID0=" 
      s-norecordsfound="Reserved Places Updated" 
      i-maxrecords="1" i-groupsize="0" botid="0" 
      u-dblib="../../_fpclass/fpdblib.inc" 
      u-dbrgn1="../../_fpclass/fpdbrgn1.inc" 
      u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
      b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
      b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" 
      sa-CritTypes b-WasTableFormat="TRUE" startspan 
      b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="update reserved_places set riga_acts=::riga_acts:: , block1=::block1:: , lastupdated=getDate()  where studioID=::studioID0::"
fp_sDefault="riga_acts=&block1=&studioID0="
fp_sNoRecords="<tr><td colspan=16 align=""LEFT"" width=""100%"">Reserved Places Updated</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&eof=130&lastupdated=135&wod_money=6&wod_datepaid=135&wod_changed=3&wod_dancers=3&wod_acts=3&event3=3&belek_money=6&belek_datepaid=135&belek_changed=3&belek_dancers=3&belek_acts=3&event2=3&riga_money=6&riga_datepaid=135&riga_changed=3&riga_dancers=3&block1=3&riga_acts=3&event1=3&studioID=3&reserveID=3&"
fp_iDisplayCols=16
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><!--webbot 
      bot="DatabaseRegionEnd" b-tableformat="TRUE" 
      b-menuformat="FALSE" 
      u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" 
      clientside tag="TBODY" 
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
      startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
				</table>
			</div>
			</td>
		</tr>
	</table>
</div>

</body>

</html>
