<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Space4Dance ~ Dance Competitions Platform</title>
<meta name="viewport" content="width=100%, initial-scale=1">
<script src="https://kit.fontawesome.com/e9d2b8eb05.js" crossorigin="anonymous"></script>
<meta http-equiv="refresh" content="8;url=../blank_signup.asp">
</head>

<body>

<table width="100%" style="font-family: Bahnschrift; font-size: 10pt">
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="email" 
  s-columntypes="202" s-dataconnection="s4d_2025" b-tableformat="TRUE" 
  b-menuformat="FALSE" s-menuchoice="email" s-menuvalue="email" 
  b-tableborder="FALSE" b-tableexpand="TRUE" b-tableheader="FALSE" 
  b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" 
  b-makeform="FALSE" s-recordsource s-displaycolumns="email" 
  s-criteria s-order 
  s-sql="select email from studios where email='::email8::'" 
  b-procedure="FALSE" clientside suggestedext="asp" 
  s-defaultfields="email8=0" s-norecordsfound i-maxrecords="1" 
  i-groupsize="0" botid="0" u-dblib="../../_fpclass/fpdblib.inc" 
  u-dbrgn1="../../_fpclass/fpdbrgn1.inc" 
  u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
  preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
  b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" 
  b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="TRUE" 
  startspan b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="select email from studios where email='::email8::'"
fp_sDefault="email8=0"
fp_sNoRecords="<tr><td colspan=1 align=""LEFT"" width=""100%""></td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="email"
fp_sMenuValue="email"
fp_sColTypes="&email=202&"
fp_iDisplayCols=1
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<p style="margin-top: 4px; margin-bottom: 4px">
			<font color="#E66A00">
			<!--webbot bot="DatabaseResultColumn" 
   s-columnnames="email" s-column="email" 
   b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" 
   clientside b-MenuFormat 
   preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;email&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
   startspan s-ColumnTypes="202" --><%=FP_FieldVal(fp_rs,"email")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font>	<font color="#FFFFFF">is already on file. </font>
			</p>
	<p style="margin-top: 4px; margin-bottom: 4px">
	<font color="#FFFFFF">Please log in to your account&nbsp; </font> 
	<a target="_parent" href="../signin.asp"><font color="#FFFFFF"><i class="fa-solid fa-right-to-bracket fa-xl" style="color: #e66a00;"></i></font></a></td>
</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" 
  b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" 
  i-groupsize="0" clientside tag="TBODY" 
  preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
  startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</body>

</html>
