<%' FP_ASP ASP Automatically generated by a FrontPage Component. Do not Edit.

On Error Resume Next
Session("FP_OldCodePage") = Session.CodePage
Session("FP_OldLCID") = Session.LCID
Session.CodePage = 1252
Err.Clear

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("s4d_2025_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "acts", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(13)
	Dim arFormDBFields0(13)
	Dim arFormValues0(13)

	arFormFields0(0) = "teamname"
	arFormDBFields0(0) = "teamname"
	arFormValues0(0) = Request("teamname")
	arFormFields0(1) = "eventID"
	arFormDBFields0(1) = "eventID"
	arFormValues0(1) = Request("eventID")
	arFormFields0(2) = "act_name"
	arFormDBFields0(2) = "actname"
	arFormValues0(2) = Request("act_name")
	arFormFields0(3) = "format"
	arFormDBFields0(3) = "act_format"
	arFormValues0(3) = Request("format")
	arFormFields0(4) = "act_agegroup"
	arFormDBFields0(4) = "act_agegroup"
	arFormValues0(4) = Request("act_agegroup")
	arFormFields0(5) = "uniqueid"
	arFormDBFields0(5) = "duplicates"
	arFormValues0(5) = Request("uniqueid")
	arFormFields0(6) = "lastupdated"
	arFormDBFields0(6) = "lastupdated"
	arFormValues0(6) = Request("lastupdated")
	arFormFields0(7) = "act_division"
	arFormDBFields0(7) = "act_division"
	arFormValues0(7) = Request("act_division")
	arFormFields0(8) = "datecreated"
	arFormDBFields0(8) = "datecreated"
	arFormValues0(8) = Request("datecreated")
	arFormFields0(9) = "eventname"
	arFormDBFields0(9) = "eventname"
	arFormValues0(9) = Request("eventname")
	arFormFields0(10) = "studioID"
	arFormDBFields0(10) = "studioID"
	arFormValues0(10) = Request("studioID")
	arFormFields0(11) = "act_nomination"
	arFormDBFields0(11) = "act_nomination"
	arFormValues0(11) = Request("act_nomination")
	arFormFields0(12) = "filler"
	arFormDBFields0(12) = "filler"
	arFormValues0(12) = Request("filler")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0


	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Session("FP_SavedFields")=arFormFields0
	Session("FP_SavedValues")=arFormValues0
	Session.CodePage = Session("FP_OldCodePage")
	Session.LCID = Session("FP_OldLCID")
	Response.Redirect "../act_confirm.asp"

End If
End If

Session.CodePage = Session("FP_OldCodePage")
Session.LCID = Session("FP_OldLCID")

%>
<!DOCTYPE html>
<html lang="en">
  <head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="../../simple.css">
<link rel="stylesheet" type="text/css" href="../../../styles.css">
<meta http-equiv="Content-Type" content="text/html; charset=Windows-1252">
<title>Space4Dance ~ Dance Competitions Platform</title>
<meta name="viewport" content="width=100%, initial-scale=1">
<script src="https://kit.fontawesome.com/e9d2b8eb05.js" crossorigin="anonymous"></script>




  <script language="JavaScript" type="text/javascript">
function gdpr()
{
        {alert("You cannot submit this form until you have read and ticked the Data Protection statement.  If you do not agree to have your data stored electronically you cannot use this form to create an online account");document.forms['FrontPage_Form1'].elements['tickmessage'].focus();}

}
</script>

<script language="JavaScript" type="text/JavaScript">
function clearbox(thebox)
{
  thebox.value = "";
}
  onfocus="clearbox(this)"

</script>

<SCRIPT Language="JavaScript">
function stopRKey(evt) {
    var evt = (evt) ? evt : ((event) ? event : null);
    var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
    if ((evt.keyCode == 13) && (node.type=="text")) {return false;}
}

document.onkeypress = stopRKey;
</SCRIPT>

<SCRIPT Language="JavaScript">
function changetoupper(a)
{ 
	a.value = a.value.toUpperCase();

}
</SCRIPT>

<SCRIPT Language="JavaScript">
function changetoproper(aa)
{
    aa.value = aa.value.charAt(0).toUpperCase() + aa.value.substr(1).toLowerCase();
}
</SCRIPT>


<link rel="stylesheet" type="text/css" href="../../simple.css">

<base target="I18">

</head>

<body topmargin="100" style="background-color: #000000">
  <div align="center"><p></div>

	<div align="center">
		<iframe name="I18" src="../blank_act_edit.asp" height="50" 
  marginwidth="1" marginheight="0" border="0" frameborder="0">
		Your browser does not support inline frames or is currently configured not to display inline frames.
		</iframe>
		<table border="0" class="div2" style="border-collapse: collapse" 
  cellspacing="3">
			<tr>
			<td>


<!--webbot BOT="GeneratedScript" PREVIEW=" " startspan --><script Language="JavaScript" Type="text/javascript"><!--
function FrontPage_Form1_Validator(theForm)
{

  if (theForm.act_ID.selectedIndex < 0)
  {
    alert("Please select one of the \"Select Act\" options.");
    theForm.act_ID.focus();
    return (false);
  }

  if (theForm.act_ID.selectedIndex == 0)
  {
    alert("The first \"Select Act\" option is not a valid selection.  Please choose one of the other options.");
    theForm.act_ID.focus();
    return (false);
  }
  return (true);
}
//--></script><!--webbot BOT="GeneratedScript" endspan --><form action="edit_act.asp" target="_self" onsubmit="return FrontPage_Form1_Validator(this)" language="JavaScript" name="FrontPage_Form1">
	<p align="center"><nobr>
	<!--webbot bot="DatabaseRegionStart" s-columnnames="act_ID,actname,filler,duplicates,lastupdated,datecreated,notes,mixedage,act_max_age,act_min_age,act_division,act_agegroup,act_nomination,comp_numbers,act_type,act_format,teamname,studioID,eventname,eventID" s-columntypes="3,202,130,202,135,135,203,130,3,3,130,130,202,3,3,130,202,3,202,3" s-dataconnection="s4d_2025" b-tableformat="FALSE" b-menuformat="TRUE" s-menuchoice="actname" s-menuvalue="act_ID" b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="act_ID,actname" s-criteria s-order s-sql="select act_ID, actname from acts where studioID = ::studioID0::&lt;br&gt;order by actname ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields="studioID0=" s-norecordsfound="No records returned." i-maxrecords="0" i-groupsize="0" botid="3" u-dblib="../../../_fpclass/fpdblib.inc" u-dbrgn1="../../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" preview=" &lt;span style=&quot;color: rgb(0,0,0); background-color: rgb(255,255,0)&quot;&gt;Database&lt;/span&gt; " b-InForm="TRUE" b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="FALSE" startspan --><!--#include file="../../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="select act_ID, actname from acts where studioID = ::studioID0:: order by actname ASC"
fp_sDefault="studioID0="
fp_sNoRecords="No records returned."
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=True
fp_sMenuChoice="actname"
fp_sMenuValue="act_ID"
fp_sColTypes="&act_ID=3&actname=202&filler=130&duplicates=202&lastupdated=135&datecreated=135&notes=203&mixedage=130&act_max_age=3&act_min_age=3&act_division=130&act_agegroup=130&act_nomination=202&comp_numbers=3&act_type=3&act_format=130&teamname=202&studioID=3&eventname=202&eventID=3&"
fp_iDisplayCols=2
fp_fCustomQuery=True
BOTID=3
fp_iRegion=BOTID
%>
<!--webbot bot="DatabaseRegionStart" endspan --><!--webbot bot="Validation" s-display-name="Select Act" b-value-required="TRUE" b-disallow-first-item="TRUE" --><select NAME="act_ID" SIZE="1" class="formfield">
	<option value="0">Select Act to Update</option>
	<!--webbot bot="AspInclude" clientside u-incfile="../../../_fpclass/fpdbrgn1.inc" startspan --><!--#include file="../../../_fpclass/fpdbrgn1.inc"--><!--webbot bot="AspInclude" endspan -->
	<option VALUE="<%=FP_FieldHTML(fp_rs,"act_ID")%>"><%=FP_FieldHTML(fp_rs,"actname")%>
	</option>
	<!--webbot bot="AspInclude" clientside u-incfile="../../../_fpclass/fpdbrgn2.inc" startspan --><!--#include file="../../../_fpclass/fpdbrgn2.inc"--><!--webbot bot="AspInclude" endspan -->
	</select><!--webbot bot="DatabaseRegionEnd" b-tableformat="FALSE" b-menuformat="TRUE" u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside preview=" &lt;span style=&quot;color: rgb(0,0,0); background-color: rgb(255,255,0)&quot;&gt;Results&lt;/span&gt; " startspan --><!--webbot bot="DatabaseRegionEnd" endspan --></nobr></p>
	<input type="hidden" name="studio_ID" 
 value="<%=Server.HtmlEncode(Request("studio_ID0"))%>"><input type="hidden" 
 name="studio_ID0" value="<%=Server.HtmlEncode(Request("studio_ID"))%>">
</form>

			</td>
			</tr>
			<tr>
				<td align="center">
				<!--webbot BOT="GeneratedScript" PREVIEW=" " startspan --><script Language="JavaScript" Type="text/javascript"><!--
function FrontPage_Form2_Validator(theForm)
{

  if (theForm.teamname.value == "")
  {
    alert("Please enter a value for the \"Studio Name\" field.");
    theForm.teamname.focus();
    return (false);
  }

  if (theForm.teamname.value.length < 1)
  {
    alert("Please enter at least 1 characters in the \"Studio Name\" field.");
    theForm.teamname.focus();
    return (false);
  }

  if (theForm.teamname.value.length > 50)
  {
    alert("Please enter at most 50 characters in the \"Studio Name\" field.");
    theForm.teamname.focus();
    return (false);
  }

  if (theForm.act_name.value == "")
  {
    alert("Please enter a value for the \"Studio Name\" field.");
    theForm.act_name.focus();
    return (false);
  }

  if (theForm.act_name.value.length < 1)
  {
    alert("Please enter at least 1 characters in the \"Studio Name\" field.");
    theForm.act_name.focus();
    return (false);
  }

  if (theForm.act_name.value.length > 50)
  {
    alert("Please enter at most 50 characters in the \"Studio Name\" field.");
    theForm.act_name.focus();
    return (false);
  }
  return (true);
}
//--></script><!--webbot BOT="GeneratedScript" endspan --><form method="POST" action="acts_edit_copy(1).asp" name="FrontPage_Form2"
   onsubmit="return FrontPage_Form2_Validator(this)" 
   language="JavaScript" target="_self" webbot-action="--WEBBOT-SELF--">
					<!--webbot bot="SaveDatabase" SuggestedExt="asp" 
    S-DataConnection="s4d_2025" S-RecordSource="acts" 
    S-Form-Fields="teamname eventID act_name format act_agegroup uniqueid lastupdated act_division datecreated eventname studioID act_nomination filler" 
    
    S-Form-DBFields="teamname eventID actname act_format act_agegroup duplicates lastupdated act_division datecreated eventname studioID act_nomination filler" 
    U-ASP-Include-Url="../../../_fpclass/fpdbform.inc" startspan 
     U-Confirmation-Url="../act_confirm.asp" --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../../../_fpclass/fpdbform.inc"--><!--webbot 
    bot="SaveDatabase" endspan i-checksum="52631" -->

	    &nbsp;<p>&nbsp;</p>
					<p>

	    <select id="eventID1" name="eventID" class=formfield onchange="updateOptions(); updateNominations(); updateAgegroups(); chkdiv(); bbb.value=this.value" onblur="uniqueid.value=<%=Server.HtmlEncode(Request("studioID0"))%>+'/'+eventID.value+'/'+teamname.value;if(this.value==7) {eventname.value='Riga';} if(this.value==8) {eventname.value='Turkey';} if(this.value==9) {eventname.value='World of Dance Latvia';};" >
        <option value="0">Select Event</option>
        <option value="7">Riga</option>
        <option value="8">Turkey</option>
        <option value="9">World of Dance Latvia</option>
    </select>
					</p>
					<p align="center" 
     style="margin-top: 6px; margin-bottom: 6px">
					&nbsp;<!--webbot bot="Validation" s-display-name="Studio Name" b-value-required="TRUE" i-minimum-length="1" i-maximum-length="50" --><input onfocus="chkfield()" type="text" placeholder="Team Name" class="formfield" name="teamname" 
    size="29" maxlength="50" onblur="changetoupper(teamname); uniqueid.value=<%=Server.HtmlEncode(Request("studioID0"))%>+'/'+eventID.value+'/'+this.value"
    tabindex="1"></p>
					<p align="center" 
     style="margin-top: 6px; margin-bottom: 6px">
					<!--webbot bot="Validation" s-display-name="Studio Name" b-value-required="TRUE" i-minimum-length="1" i-maximum-length="50" --><input  onfocus="chkfield()"  type="text" 
    placeholder="Act Name" class="formfield" name="act_name" 
    size="20" maxlength="50" tabindex="2" 
    onblur="changetoupper(act_name)"></p>
					<p align="center" 
     style="margin-top: 6px; margin-bottom: 6px">
    <select  onfocus="chkfield()"  id="formatID" name="format" class="formfield">
        <option value="0">Select Format</option>
    </select></p>
					<p align="center" 
     style="margin-top: 6px; margin-bottom: 6px">
					<select  onfocus="chkfield()"  size="1" name="act_nomination" id="nominationsID" class="formfield">
					</select></p>
					<p align="center" style="margin-top: 6px; margin-bottom: 6px">
					<select  onfocus="chkfield()"  size="1" name="act_agegroup" id="agegroupID" class="formfield">
                    </select>
					<p align="center" style="margin-top: 6px; margin-bottom: 6px">
					<select  onfocus="chkfield()" size="1" name="act_division" id="actdivID" class="formfield">
                    <option value="0">Select WOD Latvia Division</option>
                    <option value="Team">Team Division 18+</option>
                    <option value="Junior">Junior Division U18s</option>
                    <option value="Youth">Youth Division U12s</option>
                    <option value="Styles">WOD Styles</option>
                    </select>
					<p align="center">&nbsp;</p>
					<p align="center">&nbsp;</p>
					<nobr>
					<p style="margin-top: 6px; margin-bottom: 6px"></p>
					<p style="margin-top: 6px; margin-bottom: 6px">
					<p style="margin-top: 10px; ">
					<a onclick="if(aaa.value==0) {myFunc1()} else {myFunc2()}">
					<font size="2">Click on padlock&nbsp;</font><font size="2" color="#D5EAFF"><i id="icon" onclick="myFunc9(aaa)" class="fa-sharp-duotone fa-solid fa-lock-keyhole fa-2xl" style="--fa-primary-color: yellow; --fa-secondary-color: #ffffff;"></i></font><font 
     size="2">&nbsp;to unlock/lock</font></a></p>
					<p style="margin-top: 10px; ">
					<input type="submit" id="mySubmit" value="Submit" name="B1"></p>
					<p>&nbsp;</p>
					<p style="margin-top: 0; margin-bottom: 0"></p>
					<p style="margin-top: 0; margin-bottom: 0"></p>
					<input type="hidden" name="aaa" id="aaa" value="0">
					<input type="hidden" name="bbb" id="bbb" value="0">
					<input type="hidden" name="lastupdated" value="<%=now()%>">
					<input type="hidden" name="filler" value=" ">
					<input type="hidden" name="datecreated" value="<%=now()%>">
					<input type="hidden" name="uniqueid" value="">
					<input type="hidden" name="studioID" value="<%=Server.HtmlEncode(Request("studioID0"))%>">
                    <input type="hidden" name="eventname" value="">

				</form></td>
			</tr>
		</table></div>
    <script>
function myFunc1()
{
  {document.getElementById("mySubmit").disabled = false;document.getElementById("mySubmit").value="Add Act";document.getElementById("mySubmit").style.backgroundColor='green';document.getElementById("aaa").value='1';}
}
</script>

<script>
function myFunc2()
{
  	{document.getElementById("mySubmit").disabled = true;document.getElementById("mySubmit").value="Locked";document.getElementById("mySubmit").style.backgroundColor='red';document.getElementById("aaa").value='0';}
}
</script>
<script>
function myFunc9(aaa)
{
	if (aaa.value=='1') {document.getElementById("icon").className="fa-sharp-duotone fa-solid fa-lock-keyhole fa-2xl";}
	if (aaa.value=='0') {document.getElementById("icon").className="fa-sharp-duotone fa-solid fa-lock-keyhole-open fa-2xl";}
}
</script>
<script>
function myFunction2() 
{
  document.getElementById("mySubmit").disabled = true;document.getElementById("mySubmit").value="Add Act (Locked)";document.getElementById("mySubmit").style.backgroundColor='red';document.getElementById('actdivID').disabled=true;
}
window.onload = myFunction2();
</script>

      <script>
    function updateOptions() {
      const category = document.getElementById("eventID1").value;
      const itemsDropdown = document.getElementById("formatID");

      // Clear previous options
      itemsDropdown.innerHTML = '<option value="">Select Format</option>';

      // Define options for each category
      const options = {
        7: ["Group"],
        8: ["Group", "Solo", "Duo","Trio"],
        9: ["Group", "Solo", "Duo"],
      };

      // Populate the second dropdown based on the selected category
      if (options[category]) {
        options[category].forEach(item => {
          const option = document.createElement("option");
          option.value = item.toLowerCase();
          option.textContent = item;
          itemsDropdown.appendChild(option);
        });
      }
    }
    </script>
    
	<script>
    function updateNominations() {
      const category = document.getElementById("eventID1").value;
      const itemsDropdown = document.getElementById("nominationsID");
      
      // Clear previous options
      itemsDropdown.innerHTML = '<option value="">Select Nominations</option>';

      // Define options for each category
      const options = {
        7: ["Contemp & Modern", "Folk Dance", "Folk Style Dance", "Hip Hop & Urban" , "Kids' Dance", "Stage Dance"],
        8: ["Contemp & Jazz-Modern", "Folk Dance", "Folk Style Dance", "Hip Hop & Urban" , "Kids' Dance", "Stage Dance"],
        9: ["Contemp & Jazz-Modern", "Hip Hop & Urban" , "Stage Dance"],
      };

      // Populate the second dropdown based on the selected category
      if (options[category]) {
        options[category].forEach(item => {
          const option = document.createElement("option");
          option.value = item.toLowerCase();
          option.textContent = item;
          itemsDropdown.appendChild(option);
        });
      }
    }
    </script>
	<script>
function updateAgegroups() {
  const category = document.getElementById("eventID1").value;
  const itemsDropdown = document.getElementById("agegroupID");

  // Clear previous options
  itemsDropdown.innerHTML = '<option value="">Select Age Groups</option>';

  // Define options for each category
  const options = {
    7: ["3-4 Y", "5-6 Y", "7-9 Y", "10-12 Y" , "13-15 Y", "16-18 Y", "Adult 18+","Adult 35+"],
    8: ["3-4 Y", "5-6 Y", "7-9 Y", "10-12 Y" , "13-15 Y", "16-18 Y", "Adult 18+","Adult 35+"],
    9: ["Under 12s" , "Under 18s" , "Over 18s"],
  };

  // Populate the second dropdown based on the selected category
  if (options[category]) {
    options[category].forEach(item => {
      const option = document.createElement("option");
      option.value = item.toLowerCase();
      option.textContent = item;
      itemsDropdown.appendChild(option);
    });
  }
}
</script>
    <script>
        function chkdiv()
        {
        let t = document.getElementById('eventID1').value;
        if (t == 7 || t == 8) {document.getElementById("actdivID").disabled = true;}
        if (t == 9) {document.getElementById("actdivID").disabled = false;}
        }
    </script>
        <script>
        function chkfield()
        {
        let tt = document.getElementById('bbb').value;
        if (tt==0) {alert('Use Select Event first as other options on this form are dependent on your choice');document.forms['FrontPage_Form1'].elements['eventID'].focus();}
        }
    </script>
</body>
</html>