<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Europestage || we love dancing</title>
<script src="https://kit.fontawesome.com/247c7fd0d8.js" crossorigin="anonymous"></script>
</head>

<body>

<div align="center">
	<table border="0" style="border-collapse: collapse">
		<tr>
			<td align="center">

			<td align="center">
			<img border="0" src="../../studios/green-tick.png"></td>
			<td align="left">
			<div align="center">
				<table width="100%" 
    style="color: #FFFFFF; font-family: Bahnschrift; font-size: 10pt">
					<tbody>
						<!--webbot bot="DatabaseRegionStart" 
      s-columnnames="filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,city,mobile,email,surname,fname,contact,studioname,studio_ID" 
      s-columntypes="130,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,202,202,3" 
      s-dataconnection="s4d_2025" b-tableformat="TRUE" 
      b-menuformat="FALSE" s-menuchoice s-menuvalue 
      b-tableborder="FALSE" b-tableexpand="TRUE" 
      b-tableheader="FALSE" b-listlabels="TRUE" 
      b-listseparator="TRUE" i-listformat="0" 
      b-makeform="FALSE" s-recordsource s-displaycolumns 
      s-criteria s-order 
      s-sql="update studios set bulk_link='::file_link::' , bulk_uploaded=1,  lastupdated=getDate() where studio_ID=::studioID0::" 
      b-procedure="FALSE" clientside suggestedext="asp" 
      s-defaultfields="file_link=&amp;amp;studioID0=" 
      s-norecordsfound="We have received your file of dancers.  You will be able to see the full list in the 24-48 hours using the menu." 
      i-maxrecords="1" i-groupsize="0" botid="0" 
      u-dblib="../../../_fpclass/fpdblib.inc" 
      u-dbrgn1="../../../_fpclass/fpdbrgn1.inc" 
      u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
      b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
      b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" 
      sa-CritTypes b-WasTableFormat="TRUE" startspan 
      b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="update studios set bulk_link='::file_link::' , bulk_uploaded=1,  lastupdated=getDate() where studio_ID=::studioID0::"
fp_sDefault="file_link=&studioID0="
fp_sNoRecords="<tr><td colspan=16 align=""LEFT"" width=""100%"">We have received your file of dancers.  You will be able to see the full list in the 24-48 hours using the menu.</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&filler=130&bulk_uploaded=11&bulk_link=201&duplicates=202&secureno=20&sessionID=20&ipaddress=202&lastupdated=135&datecreated=135&pincode=3&instagram=202&countryID=3&city=202&mobile=202&email=202&surname=202&fname=202&contact=202&studioname=202&studio_ID=3&"
fp_iDisplayCols=16
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><!--webbot 
      bot="DatabaseRegionEnd" b-tableformat="TRUE" 
      b-menuformat="FALSE" 
      u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" i-groupsize="0" 
      clientside tag="TBODY" 
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
      startspan --><!--#include file="../../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
				</table>
			</div>
			</td>
		</tr>
	</table>
</div>

</body>

</html>
