<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Europestage || we love dancing</title>
<meta name="viewport" content="width=100%, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://kit.fontawesome.com/247c7fd0d8.js" crossorigin="anonymous"></script>

<script>setTimeout(function(){
   window.location.reload();
}, 180000);
</script>

<style type="text/css">

.div1 {
  width: 120px;
  height: 35px;
  display:table-cell;
  font-family: Bahnschrift; 
  font-size: 12pt; 
  border-radius:4px;
  border: 1px solid blue;
  background-color:#FFFFFF;
  text-align:left;
  vertical-align:middle;
}

input[type=submit] {
  width: 90px;
  height: 35px;
  background-color: #4CAF50;
  color: white;
  padding: 10px 10px;
  margin: 0px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

.div2 {
  width: 90%;
  height: 35px;
  padding: 10px;
  border-radius:12px;
  border: 1px #F0F0F0;
  background-color: #000000;

}
.button {
  border: none;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  background-color:#EAF4FF;
}
img {
	width: 120px;
	max-width: 90vw;
	height: 90px;
	object-fit: contain;
	border: 0px;
	}
.img2 {
	width: 50px;
	height: 50px;
	object-fit: contain;
	border: 0px;
	}
</style>
 </head>
<body bgcolor="#000000">

	<div align="center">
		<table width="100%" border="1" bgcolor="#FFFFFF" style="border-width:0; font-family: Trebuchet MS; font-size: 10pt; border-collapse:collapse" class="div2">
		<tr>
			<th ALIGN="LEFT" style="border-style: none; border-width: medium" colspan="2">
			<font color="#FFFFFF">&nbsp;</font><a href="stage_call.asp" target=_self><i class="fa-solid fa-arrows-rotate" style="color: #FF7600"></i></a><font color="#FFFFFF">&nbsp;<font face="Bahnschrift" size="1">Auto</font></font></th>
		</tr>
		<tr>
			<th ALIGN="LEFT" style="border-style: none; border-width: medium" colspan="2">
			<p align="center">
			<iframe name="I5" src="../blank.asp" marginwidth="1" marginheight="0" width="90%" border="0" frameborder="0" height="50">
			Your browser does not support inline frames or is currently configured not to display inline frames.
			</iframe></th>
		</tr>
		<tr>
			<th style="border-style: none; border-width: medium" colspan="2">
			<p style="margin-top: 0; margin-bottom: 0"><font color="#FFFFFF">BACKSTAGE ADMINISTRATION - STAGE CALL</font></p>
			<p style="margin-top: 0; margin-bottom: 0">
			<iframe frameborder="0" width="262" height="16" allowtransparency="true" src="https://free.timeanddate.com/clock/iaasd9z2/n602/tluk/fn16/fs12/fcff7600/tct/pct/ahl/ftb/tt0/th2" name="I6">
			</iframe></th>
		</tr>
		<tr>
			<th style="border-style: none; border-width: medium" width="100%" colspan="2">
								</th>
		</tr>
		<tr>
			<th style="border-style: none; border-width: medium" width="10%">
			<p style="margin-top: 0; margin-bottom: 0"><b>
			<font size="1" color="#FFFFFF">order</font></b></th>
			<th ALIGN="LEFT" style="border-style: none; border-width: medium" width="90%">
			<p style="margin-top: 0; margin-bottom: 0">
			<font size="1" color="#FFFFFF">act</font></th>
		</tr>
</table>
  		<p style="margin-top: 0; margin-bottom: 0">&nbsp;</p>
		<hr>
		<table width="100%" border="1" bgcolor="#FFFFFF" style="border-width:0; font-family: Trebuchet MS; font-size: 10pt; border-collapse:collapse" class="div2">
	<thead>
		<tr>
			<th style="border-style: none; border-width: medium" width="100%">
			<!--webbot bot="DatabaseRegionStart" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-columntypes="3,3,3,200,202,202,202,130,202,130,130,130,3" s-dataconnection="s4d_2025" b-tableformat="FALSE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="FALSE" b-listseparator="FALSE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-criteria s-order s-sql="SELECT act_ID, studioID, program_order, left(starttime,5) as starttime, studioname, teamname, actname, act_format, act_nomination, act_agegroup,  acts.filler, mixedage , block FROM acts&lt;br&gt;LEFT JOIN studios on studio_ID=studioID&lt;br&gt;left join ESstage on actId=act_ID&lt;br&gt;where statusnumber= 4 and eventID=7&lt;br&gt;ORDER BY program_order DESC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No Acts Currently on Stage.  Block Not Started" i-maxrecords="1" i-groupsize="0" botid="1" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="BODY" preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" startspan --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT act_ID, studioID, program_order, left(starttime,5) as starttime, studioname, teamname, actname, act_format, act_nomination, act_agegroup,  acts.filler, mixedage , block FROM acts LEFT JOIN studios on studio_ID=studioID left join ESstage on actId=act_ID where statusnumber= 4 and eventID=7 ORDER BY program_order DESC"
fp_sDefault=""
fp_sNoRecords="No Acts Currently on Stage.  Block Not Started"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&act_ID=3&studioID=3&program_order=3&starttime=200&studioname=202&teamname=202&actname=202&act_format=130&act_nomination=202&act_agegroup=130&filler=130&mixedage=130&block=3&"
fp_iDisplayCols=13
fp_fCustomQuery=True
BOTID=1
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><table width="100%" border="1" bgcolor="#FFFFFF" style="border-width:0; font-family: Trebuchet MS; font-size: 10pt; border-collapse:collapse; width:100%" class="div2">
	<tr>
			<td style="border-style: none; border-width: medium" align="center" width="100%" colspan="3">
			&nbsp;</td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%">
			&nbsp;</td>
			<td style="border-style: none; border-width: medium" width="70%">
			<b><font size="3" color="#FFFFFF">ACT NOW ON STAGE</font></b></td>
			<td style="border-style: none; border-width: medium" width="20%" rowspan="4" align="center">
			<i class="fa-solid fa-circle fa-2xl" style="color: hsl(116, 90%, 47%);"></i></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%">
			<div style="position: absolute; width: 129px; height: 78px; z-index: 2; left: 5px; visibility:visible; bottom:5px" id="s4d_logo" align="left">
				<img src="../../images/s4d_logo.jpg"></div>

			<div style="position: absolute; width: 85px; height: 56px; z-index: 1; right: 15px; float: right; visibility:visible; top:5px" 
id="es_logo">
	<p style="margin-top: 6px; margin-bottom: 6px">
	<img border="0" class="img2" src="../../myaccount/studios/ES_60.png" align=right></div>

			<font color="#FF7600">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="program_order" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;program_order&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"program_order")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
			<td style="border-style: none; border-width: medium" width="70%">
			<font color="#FF7600">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="actname" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;actname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,3,3,200,202,202,202,130,202,130,130,130,3" --><%=FP_FieldVal(fp_rs,"actname")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font><font color="#FFFFFF"><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="teamname" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;teamname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,200,202,202,202,202,202,202,130,202,130,130,130,11,202,202,202,130,130,3,203,202,203,202,3,11,202,202,135,135,3,202,202,202,3,202,202,202,202,3,135,135,17,17,3,3,3,203,11,202,3,3,3,3,3" --><%=FP_FieldVal(fp_rs,"teamname")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%">
			<font color="#FFFFFF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="starttime" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;starttime&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,3,3,200,202,202,202,130,202,130,130,130,3" --><%=FP_FieldVal(fp_rs,"starttime")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
			<td style="border-style: none; border-width: medium" width="70%">
			<font color="#FFFFFF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="mixedage" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;mixedage&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"mixedage")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="act_agegroup" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_agegroup&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_agegroup")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,teamname,act_name,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="act_nomination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_nomination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_nomination")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%">
					</td>
			<td style="border-style: none; border-width: medium" width="70%">
			<font color="#FFFFFF">
			<b>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="studioname" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;studioname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" s-ColumnTypes="3,3,3,200,202,202,202,130,202,130,130,130,3" startspan --><%=FP_FieldVal(fp_rs,"studioname")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></b></font></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" colspan="3">
			&nbsp;</td>
		</tr>
</table>

			<!--webbot bot="DatabaseRegionEnd" b-tableformat="FALSE" b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="BODY" preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></th>
		</tr>
	</thead>
</table>
  		<hr>
  </div>
			<form method="POST" action="update_stage.asp" name="formbackstage" target="I5">
	<div align="center">
		<!--webbot bot="DatabaseRegionStart" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-columntypes="3,3,3,200,202,202,202,130,202,130,130,130,3" s-dataconnection="s4d_2025" b-tableformat="FALSE" b-menuformat="FALSE" s-menuchoice="act_ID" s-menuvalue="act_ID" b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="FALSE" b-listseparator="FALSE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-criteria s-order s-sql="SELECT act_ID, studioID, program_order, left(starttime,5) as starttime, studioname, teamname, actname, act_format, act_nomination, act_agegroup,  acts.filler, mixedage , block FROM acts&lt;br&gt;LEFT JOIN studios on studio_ID=studioID&lt;br&gt;left join ESstage on actId=act_ID&lt;br&gt;where statusnumber= 1 and eventID=7&lt;br&gt;ORDER BY program_order ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No further Acts Reported" i-maxrecords="1" i-groupsize="0" botid="0" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="BODY" preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" startspan b-InForm="TRUE" b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT act_ID, studioID, program_order, left(starttime,5) as starttime, studioname, teamname, actname, act_format, act_nomination, act_agegroup,  acts.filler, mixedage , block FROM acts LEFT JOIN studios on studio_ID=studioID left join ESstage on actId=act_ID where statusnumber= 1 and eventID=7 ORDER BY program_order ASC"
fp_sDefault=""
fp_sNoRecords="No further Acts Reported"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=False
fp_sMenuChoice="act_ID"
fp_sMenuValue="act_ID"
fp_sColTypes="&act_ID=3&studioID=3&program_order=3&starttime=200&studioname=202&teamname=202&actname=202&act_format=130&act_nomination=202&act_agegroup=130&filler=130&mixedage=130&block=3&"
fp_iDisplayCols=13
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><table width="100%" border="1" bgcolor="#FFFFFF" style="border-width:0; font-family: Trebuchet MS; font-size: 10pt; border-collapse:collapse; " class="div2">
	<tr>
			<td style="border-style: none; border-width: medium" align="center" width="100%" colspan="3">
			&nbsp;</td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%" height="25">
			&nbsp;</td>
			<td style="border-style: none; border-width: medium" width="70%" height="25">
			<font color="#FFFFFF" size="3">Next Up</font></td>
			<td style="border-style: none; border-width: medium" width="20%" align="center" rowspan="4">
			<p style="margin-top: 0; margin-bottom: 0">
			<input type="submit" value="Submit" id="mySubmit1" name="B3"></p>
			</td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%" height="25">
			<font color="#FFFFFF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="program_order" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;program_order&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"program_order")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
			<td style="border-style: none; border-width: medium" width="70%" height="25">
			<font color="#FFFFFF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="actname" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;actname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,3,3,200,202,202,202,130,202,130,130,130,3" --><%=FP_FieldVal(fp_rs,"actname")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="filler" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="teamname" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;teamname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,200,202,202,202,202,202,202,130,202,130,130,130,11,202,202,202,130,130,3,203,202,203,202,3,11,202,202,135,135,3,202,202,202,3,202,202,202,202,3,135,135,17,17,3,3,3,203,11,202,3,3,3,3,3" --><%=FP_FieldVal(fp_rs,"teamname")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%">
			<font color="#FFFFFF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="starttime" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;starttime&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,3,3,200,202,202,202,130,202,130,130,130,3" --><%=FP_FieldVal(fp_rs,"starttime")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
			<td style="border-style: none; border-width: medium" width="70%">
			<font color="#FFFFFF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="mixedage" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;mixedage&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"mixedage")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="filler" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="act_agegroup" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_agegroup&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_agegroup")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="filler" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
   bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="act_nomination" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_nomination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_nomination")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" width="10%">
					&nbsp;</td>
			<td style="border-style: none; border-width: medium" width="70%">
			<font color="#FFFFFF">
			<b>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,starttime,studioname,teamname,actname,act_format,act_nomination,act_agegroup,filler,mixedage,block" s-column="studioname" b-tableformat="FALSE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;studioname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" s-ColumnTypes="3,3,3,200,202,202,202,130,202,130,130,130,3" startspan --><%=FP_FieldVal(fp_rs,"studioname")%><!--webbot 
   bot="DatabaseResultColumn" endspan --></b></font></td>
		</tr>
		<tr>
			<td style="border-style: none; border-width: medium" align="center" colspan="3">
			&nbsp;</td>
		</tr>
</table>
  	<input type="hidden" name="aaa" id="aaa" value="0">
	<input type="hidden" name="actualTOS" value="<%=now()+.0416667%>">
	  <input type="hidden" name="act_ID" value="<%=FP_FieldVal(fp_rs,"act_ID")%>">
		<hr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="FALSE" b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="BODY" preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></div>

	</form>

			

	</body>

</html>