<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>onTrack with YDL</title>
<base target="I1">
<style>
<!--
 table.MsoNormalTable
	{mso-style-parent:"";
	font-size:10.0pt;
	font-family:"Times New Roman",serif}
 p.MsoNormal
	{mso-style-parent:"";
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	margin-left:0cm; margin-right:0cm; margin-top:0cm}
-->
</style>
</head>

<body bgcolor="#000000" topmargin="2">

					<table width="100%" 
     style="border-collapse: collapse; font-family: Bahnschrift; font-size: 9pt; border-left-width: 0px; border-right-width: 0px; border-top-width: 0px" 
     cellpadding="0" border="1">
						<tr>
							<td style="border-left-style: none; border-left-width: medium; border-right-style: none; border-right-width: medium; border-top-style: none; border-top-width: medium">
							<font color="#FFFFFF">STUDIOS</font></td>
						</tr>
						<!--webbot bot="DatabaseRegionStart" 
      s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
      s-columntypes="202,202,3,3,3,3,3,3,130,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,3,130,135,6,135,3,3,3,3,6,135,3,3,3,3,6,135,3,3,3,3,3,3" 
      s-dataconnection="s4d_2025" b-tableformat="TRUE" 
      b-menuformat="FALSE" s-menuchoice="studioname" 
      s-menuvalue="studioname" b-tableborder="FALSE" 
      b-tableexpand="TRUE" b-tableheader="FALSE" 
      b-listlabels="TRUE" b-listseparator="TRUE" 
      i-listformat="0" b-makeform="FALSE" s-recordsource 
      
      s-displaycolumns="studioname,city,total1,total2,total3,total4,total5,total6" 
      s-criteria s-order 
      s-sql="SELECT studioname, city , sum(riga_acts) as total1, sum(belek_acts) as total2, sum(wod_acts) as total3 , sum(riga_dancers) as total4, sum(belek_dancers) as total5, sum(wod_dancers) as total6 FROM reserved_places&lt;br&gt;left join studios on studio_ID=studioID&lt;br&gt;group by studioname, city, studioID , event1, event2, event3 , riga_acts, belek_acts, wod_acts, riga_dancers, belek_dancers, wod_dancers &lt;br&gt;having (event1=::event:: AND riga_acts&amp;gt;0) or (event2=::event:: and belek_acts&amp;gt;0) or (event3=::event:: and wod_acts&amp;gt;0)&lt;br&gt;order by studioname ASC" 
      b-procedure="FALSE" clientside suggestedext="asp" 
      s-defaultfields="event=&amp;amp;event=&amp;amp;event=" 
      s-norecordsfound="No studios listed" i-maxrecords="0" 
      i-groupsize="0" botid="0" 
      u-dblib="../_fpclass/fpdblib.inc" 
      u-dbrgn1="../_fpclass/fpdbrgn1.inc" 
      u-dbrgn2="../_fpclass/fpdbrgn2.inc" tag="TBODY" 
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
      b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
      b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" 
      sa-CritTypes b-WasTableFormat="TRUE" startspan 
      b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT studioname, city , sum(riga_acts) as total1, sum(belek_acts) as total2, sum(wod_acts) as total3 , sum(riga_dancers) as total4, sum(belek_dancers) as total5, sum(wod_dancers) as total6 FROM reserved_places left join studios on studio_ID=studioID group by studioname, city, studioID , event1, event2, event3 , riga_acts, belek_acts, wod_acts, riga_dancers, belek_dancers, wod_dancers  having (event1=::event:: AND riga_acts>0) or (event2=::event:: and belek_acts>0) or (event3=::event:: and wod_acts>0) order by studioname ASC"
fp_sDefault="event=&event=&event="
fp_sNoRecords="<tr><td colspan=8 align=""LEFT"" width=""100%"">No studios listed</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="studioname"
fp_sMenuValue="studioname"
fp_sColTypes="&studioname=202&city=202&total1=3&total2=3&total3=3&total4=3&total5=3&total6=3&filler=130&bulk_uploaded=11&bulk_link=201&duplicates=202&secureno=20&sessionID=20&ipaddress=202&lastupdated=135&datecreated=135&pincode=3&instagram=202&countryID=3&mobile=202&email=202&surname=202&fname=202&contact=202&studio_ID=3&eof=130&lastupdated=135&wod_money=6&wod_datepaid=135&wod_changed=3&wod_dancers=3&wod_acts=3&event3=3&belek_money=6&belek_datepaid=135&belek_changed=3&belek_dancers=3&belek_acts=3&event2=3&riga_money=6&riga_datepaid=135&riga_changed=3&riga_dancers=3&riga_acts=3&event1=3&studioID=3&reserveID=3&"
fp_iDisplayCols=8
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
							<td style="border-left-style: none; border-left-width: medium; border-right-style: none; border-right-width: medium; border-bottom-style: solid; border-bottom-width: 1px">
							<font color="#FFFFFF">
							<!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="studioname" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;studioname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       startspan --><%=FP_FieldVal(fp_rs,"studioname")%><!--webbot 
       bot="DatabaseResultColumn" endspan -->, 
							<!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="city" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;city&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       startspan --><%=FP_FieldVal(fp_rs,"city")%><!--webbot 
       bot="DatabaseResultColumn" endspan --> [</font><font 
       color="#00FFFF"> <!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="total1" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total1&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       s-ColumnTypes="202,202,3,3,3,130,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,3,130,135,6,135,3,3,3,3,6,135,3,3,3,3,6,135,3,3,3,3,3,3" 
       startspan --><%=FP_FieldVal(fp_rs,"total1")%><!--webbot 
       bot="DatabaseResultColumn" endspan -->/<!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="total4" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total4&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       startspan --><%=FP_FieldVal(fp_rs,"total4")%><!--webbot 
       bot="DatabaseResultColumn" endspan --></font><font color="#FFFFFF">&nbsp; </font>
							<font color="#00FF00">
							<!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="total2" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total2&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       s-ColumnTypes="202,202,3,3,3,130,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,3,130,135,6,135,3,3,3,3,6,135,3,3,3,3,6,135,3,3,3,3,3,3" 
       startspan --><%=FP_FieldVal(fp_rs,"total2")%><!--webbot 
       bot="DatabaseResultColumn" endspan -->/<!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="total5" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total5&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       startspan --><%=FP_FieldVal(fp_rs,"total5")%><!--webbot 
       bot="DatabaseResultColumn" endspan --></font><font color="#FFFFFF">&nbsp;&nbsp;</font><font color="#FF00FF"><!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="total3" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total3&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       s-ColumnTypes="202,202,3,3,3,130,11,201,202,20,20,202,135,135,3,202,3,202,202,202,202,202,3,130,135,6,135,3,3,3,3,6,135,3,3,3,3,6,135,3,3,3,3,3,3" 
       startspan --><%=FP_FieldVal(fp_rs,"total3")%><!--webbot 
       bot="DatabaseResultColumn" endspan -->/<!--webbot bot="DatabaseResultColumn" 
       s-columnnames="studioname,city,total1,total2,total3,total4,total5,total6,filler,bulk_uploaded,bulk_link,duplicates,secureno,sessionID,ipaddress,lastupdated,datecreated,pincode,instagram,countryID,mobile,email,surname,fname,contact,studio_ID,eof,lastupdated,wod_money,wod_datepaid,wod_changed,wod_dancers,wod_acts,event3,belek_money,belek_datepaid,belek_changed,belek_dancers,belek_acts,event2,riga_money,riga_datepaid,riga_changed,riga_dancers,riga_acts,event1,studioID,reserveID" 
       s-column="total6" b-tableformat="TRUE" 
       b-hashtml="FALSE" b-makelink="FALSE" clientside 
       b-MenuFormat 
       preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;total6&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
       startspan --><%=FP_FieldVal(fp_rs,"total6")%><!--webbot 
       bot="DatabaseResultColumn" endspan --></font><font color="#FFFFFF">
							] </font></td>
						</tr>
						<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" 
      b-menuformat="FALSE" 
      u-dbrgn2="../_fpclass/fpdbrgn2.inc" i-groupsize="0" 
      clientside tag="TBODY" 
      preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
      startspan --><!--#include file="../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></table>
					</body>
</html>