<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "utf-8"
FP_CodePage = 65001 %>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<script src="https://kit.fontawesome.com/e9d2b8eb05.js" crossorigin="anonymous"></script>
<title>Europestage || we love dancing</title>
<style>
input[type="checkbox"].unselectable {
pointer-events: none; /* Disables pointer interactions */
opacity: 0.6; /* Optional: visually indicate it's disabled */
}
</style>
<link rel="stylesheet" type="text/css" href="../simple.css">
<link rel="stylesheet" type="text/css" href="../../styles_v1.css">
<base target="_self">
</head>

<body link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" style="background-color: #000000">

<div align="center">
	<blockquote>
	<table width="100%" class="div2" style="color: #FFFFFF; border-bottom-width:0px; ">
			<tr>
				<th><font color="#FF7B00" size="3">ES RIGA</font></th>
			</tr>
			<tr>
				<th style="border-bottom-style: solid; border-bottom-width: 1px">act 
				<font color="#99CCFF">/</font> team <font color="#99CCFF">/</font> 
				age group</th>
			</tr>
			<tr>
				<th style="border-bottom-style: none; border-bottom-width: medium">
				Search Day 2 Programme by Nomination &amp; Age Group</th>
			</tr>
			<tr>
				<th style="border-bottom-style: none; border-bottom-width: medium; border-top-style:none; border-top-width:medium">
				<form action="events_search2.asp" target="_self">
					<p style="margin-top: 0; margin-bottom: 0"><nobr>
					<!--webbot bot="DatabaseRegionStart" s-columnnames="act_nomination" s-columntypes="202" s-dataconnection="s4d_2025" b-tableformat="FALSE" b-menuformat="TRUE" s-menuchoice="act_nomination" s-menuvalue="act_nomination" b-tableborder="FALSE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="act_nomination" s-criteria s-order s-sql="SELECT distinct(act_nomination) from acts where eventID=7&lt;br&gt;order by act_nomination ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="0" i-groupsize="0" botid="0" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" preview=" &lt;span style=&quot;color: rgb(0,0,0); background-color: rgb(255,255,0)&quot;&gt;Database&lt;/span&gt; " b-InForm="TRUE" b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="FALSE" b-ReplaceDatabaseRegion="FALSE" startspan --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT distinct(act_nomination) from acts where eventID=7 order by act_nomination ASC"
fp_sDefault=""
fp_sNoRecords="No records returned."
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=True
fp_sMenuChoice="act_nomination"
fp_sMenuValue="act_nomination"
fp_sColTypes="&act_nomination=202&"
fp_iDisplayCols=1
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--webbot bot="DatabaseRegionStart" endspan --><select NAME="act_nomination" SIZE="1" class="formfielddrop">
					<option value="<%=Server.HtmlEncode(Request("act_nomination"))%>"><%=Server.HtmlEncode(Request("act_nomination"))%>
					</option>
					<!--webbot bot="AspInclude" clientside u-incfile="../../_fpclass/fpdbrgn1.inc" startspan --><!--#include file="../../_fpclass/fpdbrgn1.inc"--><!--webbot bot="AspInclude" endspan -->
					<option><%=FP_FieldHTML(fp_rs,"act_nomination")%></option>
					<!--webbot bot="AspInclude" clientside u-incfile="../../_fpclass/fpdbrgn2.inc" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"--><!--webbot bot="AspInclude" endspan -->
					</select><!--webbot bot="DatabaseRegionEnd" b-tableformat="FALSE" b-menuformat="TRUE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside preview=" &lt;span style=&quot;color: rgb(0,0,0); background-color: rgb(255,255,0)&quot;&gt;Results&lt;/span&gt; " startspan --><!--webbot bot="DatabaseRegionEnd" endspan --></nobr></p>
					<p style="margin-top: 0; margin-bottom: 0"><nobr>
					<!--webbot bot="DatabaseRegionStart" s-columnnames="act_agegroup" s-columntypes="130" s-dataconnection="s4d_2025" b-tableformat="FALSE" b-menuformat="TRUE" s-menuchoice="act_agegroup" s-menuvalue="act_agegroup" b-tableborder="FALSE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="act_agegroup" s-criteria s-order s-sql="SELECT distinct(act_agegroup) from acts &lt;br&gt;left join ESstage on actID=act_ID&lt;br&gt;where eventID=7 and day=2&lt;br&gt;order by act_agegroup ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="0" i-groupsize="0" botid="5" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" preview=" &lt;span style=&quot;color: rgb(0,0,0); background-color: rgb(255,255,0)&quot;&gt;Database&lt;/span&gt; " startspan --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT distinct(act_agegroup) from acts  left join ESstage on actID=act_ID where eventID=7 and day=2 order by act_agegroup ASC"
fp_sDefault=""
fp_sNoRecords="No records returned."
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=True
fp_sMenuChoice="act_agegroup"
fp_sMenuValue="act_agegroup"
fp_sColTypes="&act_agegroup=130&"
fp_iDisplayCols=1
fp_fCustomQuery=True
BOTID=5
fp_iRegion=BOTID
%>
<!--webbot bot="DatabaseRegionStart" endspan --><select NAME="act_agegroup" SIZE="1"  onchange="submit()" class="formfielddrop">
					<option value="<%=Server.HtmlEncode(Request("act_agegroup"))%>"><%=Server.HtmlEncode(Request("act_agegroup"))%>
					</option>
					<!--webbot bot="AspInclude" clientside u-incfile="../../_fpclass/fpdbrgn1.inc" startspan --><!--#include file="../../_fpclass/fpdbrgn1.inc"--><!--webbot bot="AspInclude" endspan -->
					<option><%=FP_FieldHTML(fp_rs,"act_agegroup")%></option>
					<!--webbot bot="AspInclude" clientside u-incfile="../../_fpclass/fpdbrgn2.inc" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"--><!--webbot bot="AspInclude" endspan -->
					</select><!--webbot bot="DatabaseRegionEnd" b-tableformat="FALSE" b-menuformat="TRUE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside preview=" &lt;span style=&quot;color: rgb(0,0,0); background-color: rgb(255,255,0)&quot;&gt;Results&lt;/span&gt; " startspan --><!--webbot bot="DatabaseRegionEnd" endspan --></nobr></p>
				</form>
				</th>
			</tr>
	</table>
	</blockquote>
	<table width="100%" class="div2" style="color: #FFFFFF; border-bottom-width:0px; ">
		<thead>
		</thead>
		<tbody>
			<!--webbot bot="DatabaseRegionStart" 
   s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
   s-columntypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,130,11,135,130,3,135,135,202,3,130,3,202,202,202,202,202,202,202,3,202,3,135,135,202,20,20,202,201,11,6,6,6,6,6,6,202,203,202,203,130,3,202,130,130,3,3,202,130,202,130,130,202,130,3,202,3,202,130,202,202,130,200,3" 
   s-dataconnection="s4d_2025" b-tableformat="TRUE" 
   b-menuformat="FALSE" s-menuchoice="act_ID" s-menuvalue="act_ID" 
   b-tableborder="FALSE" b-tableexpand="TRUE" b-tableheader="TRUE" 
   b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" 
   b-makeform="FALSE" s-recordsource 
   s-displaycolumns="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
   s-criteria s-order 
   s-sql="SELECT * , left(starttime,5) as starttime , program_order-(block*1000) as programorder FROM acts &lt;br&gt;left join ESstage on actID=act_ID&lt;br&gt;left join studios on studios.studio_ID=acts.studioID&lt;br&gt;left join countries on country_ID= countryID&lt;br&gt;where eventID=7 and act_nomination ='::act_nomination::' and day=2 and act_agegroup='::act_agegroup::'&lt;br&gt;order by program_order ASC" 
   b-procedure="FALSE" clientside suggestedext="asp" 
   s-defaultfields="act_nomination=xxx&amp;amp;act_agegroup=xxx" 
   s-norecordsfound="No act for that combination of nomination &amp;amp; age group" i-maxrecords="0" 
   i-groupsize="0" botid="4" u-dblib="../../_fpclass/fpdblib.inc" 
   u-dbrgn1="../../_fpclass/fpdbrgn1.inc" 
   u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
   b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes 
   b-WasTableFormat="TRUE" startspan b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * , left(starttime,5) as starttime , program_order-(block*1000) as programorder FROM acts  left join ESstage on actID=act_ID left join studios on studios.studio_ID=acts.studioID left join countries on country_ID= countryID where eventID=7 and act_nomination ='::act_nomination::' and day=2 and act_agegroup='::act_agegroup::' order by program_order ASC"
fp_sDefault="act_nomination=xxx&act_agegroup=xxx"
fp_sNoRecords="<tr><td colspan=96 align=""LEFT"" width=""100%"">No act for that combination of nomination & age group</td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="act_ID"
fp_sMenuValue="act_ID"
fp_sColTypes="&act_ID=3&eventID=3&eventname=202&studioID=3&teamname=202&choreographer=202&actname=202&act_format=130&act_type=3&comp_numbers=3&act_nomination=202&act_agegroup=130&act_division=130&act_min_age=3&act_max_age=3&act_duration=130&mixed=11&mixedage=130&music_on_entry=202&notes=203&sound_link=201&background_link=201&combined=11&datecreated=135&lastupdated=135&duplicates=202&filler=130&ESstage_ID=3&actID=3&day=3&starttime=202&program_order=3&block=3&category=130&registered=11&reg_time=135&act_status=130&statusnumber=3&checktimeon=135&checktimeoff=135&svrdate=202&studio_ID=3&filler=130&studio_ID=3&studioname=202&contact=202&fname=202&surname=202&email=202&mobile=202&city=202&countryID=3&instagram=202&pincode=3&datecreated=135&lastupdated=135&ipaddress=202&sessionID=20&secureno=20&duplicates=202&bulk_link=201&bulk_uploaded=11&discount_lv=6&deposit_lv=6&discount_tr=6&deposit_tr=6&discount_wod=6&deposit_wod=6&company_name=202&invoice_address=203&company_number=202&invoice_notes=203&filler=130&country_ID=3&name=202&iso3=130&iso2=130&numeric_code=3&phonecode=3&capital=202&currency=130&currency_name=202&currency_symbol=130&tld=130&native=202&region=130&region_id=3&subregion=202&subregion_id=3&nationality=202&emoji=130&emojiU=202&flag=202&filler=130&starttime=200&programorder=3&"
fp_iDisplayCols=96
fp_fCustomQuery=True
BOTID=4
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
				<td width="100%" style="border-bottom-style: solid; border-bottom-width: 1px">
				<p style="margin-top: 6px; margin-bottom:6px">
				<font color="#FF7B00">
				<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="block" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;block&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130,3,202,202,202,202,202,202,202,3,202,3,135,135,202,20,20,202,201,11,6,6,6,6,6,6,202,203,202,203,130,3,202,130,130,3,3,202,130,202,130,130,202,130,3,202,3,202,130,202,202,130,200,3" --><%=FP_FieldVal(fp_rs,"block")%><!--webbot 
    bot="DatabaseResultColumn" endspan -->-<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="programorder" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;programorder&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130,200,3" --><%=FP_FieldVal(fp_rs,"programorder")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font color="#99CCFF"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="starttime" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;starttime&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130" --><%=FP_FieldVal(fp_rs,"starttime")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><font color="#99CCFF"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font color="#FFFFFF"><!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="actname" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;actname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"actname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font color="#99CCFF"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan -->/<!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font color="#FFFFFF"><!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="teamname" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;teamname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"teamname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font color="#99CCFF"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan -->/<!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="act_agegroup" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_agegroup&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"act_agegroup")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="mixedage" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;mixedage&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130,3,202,202,202,202,202,202,202,3,202,3,135,135,202,20,20,202,201,11,6,6,6,6,6,6,202,203,202,203,130,3,202,130,130,3,3,202,130,202,130,130,202,130,3,202,3,202,130,202,202,130,200,3" --><%=FP_FieldVal(fp_rs,"mixedage")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><p style="margin-top: 6px; margin-bottom:6px">
				<font color="#FFFFFF">
				<!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="studioname" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;studioname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130,3,202,202,202,202,202,202,202,3,202,3,135,135,202,20,20,202,201,11,6,6,6,6,6,6,202,203,202,203,130,200,3" --><%=FP_FieldVal(fp_rs,"studioname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font color="#99CCFF"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><span style="font-variant: small-caps"><font color="#FFFFFF"><!--webbot bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="name" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130,3,202,202,202,202,202,202,202,3,202,3,135,135,202,20,20,202,201,11,6,6,6,6,6,6,202,203,202,203,130,3,202,130,130,3,3,202,130,202,130,130,202,130,3,202,3,202,130,202,202,130,200,3" --><%=FP_FieldVal(fp_rs,"name")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font></span><font color="#99CCFF"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><font face="Arial"><!--webbot 
    bot="DatabaseResultColumn" 
    s-columnnames="act_ID,eventID,eventname,studioID,teamname,choreographer,actname,act_format,act_type,comp_numbers,act_nomination,act_agegroup,act_division,act_min_age,act_max_age,act_duration,mixed,mixedage,music_on_entry,notes,sound_link,background_link,combined,datecreated,lastupdated,duplicates,filler,ESstage_ID,actID,day,starttime,program_order,block,category,registered,reg_time,act_status,statusnumber,checktimeon,checktimeoff,svrdate,studio_ID,filler,studio_ID,studioname,contact,fname,surname,email,mobile,city,countryID,instagram,pincode,datecreated,lastupdated,ipaddress,sessionID,secureno,duplicates,bulk_link,bulk_uploaded,discount_lv,deposit_lv,discount_tr,deposit_tr,discount_wod,deposit_wod,company_name,invoice_address,company_number,invoice_notes,filler,country_ID,name,iso3,iso2,numeric_code,phonecode,capital,currency,currency_name,currency_symbol,tld,native,region,region_id,subregion,subregion_id,nationality,emoji,emojiU,flag,filler,starttime,programorder" 
    s-column="emoji" b-tableformat="TRUE" b-hashtml="TRUE" 
    b-makelink="FALSE" clientside b-MenuFormat 
    preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;emoji&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" 
    startspan s-ColumnTypes="3,3,202,3,202,202,202,130,3,3,202,130,130,3,3,130,11,130,202,203,201,201,11,135,135,202,130,3,3,3,202,3,3,135,130,3,135,135,135,130,3,202,202,202,202,202,202,202,3,202,3,135,135,202,20,20,202,201,11,6,6,6,6,6,6,202,203,202,203,130,3,202,130,130,3,3,202,130,202,130,130,202,130,3,202,3,202,130,202,202,130,200,3" --><%=FP_Field(fp_rs,"emoji")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font></td>
			</tr>
			<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" 
   b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" 
   i-groupsize="0" clientside tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
	</table>

</div>

</body>

</html>
