<html>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>New Page 1</title>
<link rel="stylesheet" type="text/css" href="../../styles.css">
<link rel="stylesheet" type="text/css" href="../simple.css">

<style>
	.button2 {
            text-align: left;
            font-family: "Roboto", sans-serif;
            font-size: 10pt;
            font-weight: 500;
            width: fit-content;
            border: 1px solid #ff7b00;
            outline: none;
            padding: 4px;
            border-radius: 4px;
            cursor: pointer;
            background: #ff7b0000;
            color: white !important;
            box-shadow: 0 0 0 1px var(--borColor) inset;
        }
            .button2:hover {
                background: #6279e7;
                border-color: #6279e7;
                transform: translateY(-1px);
                transition: ease-in-out;
            }

</style>
</head>

<body style="background-color: #000000">

<div align="center">

<table width="100%" border="1" cellspacing="0" cellpadding="0" class="div2" style="border-color:#FFFFFF; border-collapse: collapse; border-width: 1px; ">
	<thead>
		<tr>
			<th ALIGN="LEFT" style="border-style: none; border-width: medium">
			<table width="100%">
				<tbody>
					<!--webbot bot="DatabaseRegionStart" s-columnnames="dancer,filler,duplicates,lastupdated,datecreated,year_dob,mm_dob,dd_dob,dateofbirth,dancer_ln,dancer_fn,studioID,dancer_ID" s-columntypes="202,130,202,135,135,3,3,3,202,202,202,3,3" s-dataconnection="s4d_2025" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="FALSE" b-tableexpand="TRUE" b-tableheader="FALSE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="dancer" s-criteria s-order s-sql="SELECT dancer_ln+filler+dancer_fn as dancer FROM dancers where dancer_ID=::dancer_ID::" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields="dancer_ID=0" s-norecordsfound i-maxrecords="1" i-groupsize="0" botid="1" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT dancer_ln+filler+dancer_fn as dancer FROM dancers where dancer_ID=::dancer_ID::"
fp_sDefault="dancer_ID=0"
fp_sNoRecords="<tr><td colspan=1 align=""LEFT"" width=""100%""></td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&dancer=202&filler=130&duplicates=202&lastupdated=135&datecreated=135&year_dob=3&mm_dob=3&dd_dob=3&dateofbirth=202&dancer_ln=202&dancer_fn=202&studioID=3&dancer_ID=3&"
fp_iDisplayCols=1
fp_fCustomQuery=True
BOTID=1
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
						<td><font color="#D97706">
						<!--webbot bot="DatabaseResultColumn" s-columnnames="dancer,filler,duplicates,lastupdated,datecreated,year_dob,mm_dob,dd_dob,dateofbirth,dancer_ln,dancer_fn,studioID,dancer_ID" s-column="dancer" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;dancer&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"dancer")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
					</tr>
					<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
			</table>
			</th>
		</tr>
		<tr>
			<th ALIGN="LEFT" style="border-style: none; border-width: medium"><b>act name</b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="actname,eventname,filler,duplicates,lastupdated,datecreated,combined,background_link,sound_link,notes,music_on_entry,mixedage,mixed,act_duration,act_max_age,act_min_age,act_division,act_agegroup,act_nomination,comp_numbers,act_type,act_format,choreographer,teamname,studioID,eventID,act_ID,filler,session,actdancerID,declared,all_dancerID,all_act_ID,all_studioID,all_eventID,declare_ID" s-columntypes="202,202,130,202,135,135,11,201,201,203,202,130,11,130,3,3,130,130,202,3,3,130,202,202,3,3,3,130,20,130,11,3,3,3,3,3" s-dataconnection="s4d_2025" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="actname" s-menuvalue="actname" b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="actname,eventname" s-criteria s-order s-sql="SELECT actname, eventname FROM allocations&lt;br&gt;left join acts on act_ID = all_act_ID&lt;br&gt;where all_dancerID = ::dancer_ID:: &lt;br&gt;order by actname ASC&lt;br&gt;" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields="dancer_ID=0" s-norecordsfound="Dancer not allocated to any act " i-maxrecords="0" i-groupsize="0" botid="0" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="TRUE" b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT actname, eventname FROM allocations left join acts on act_ID = all_act_ID where all_dancerID = ::dancer_ID::  order by actname ASC "
fp_sDefault="dancer_ID=0"
fp_sNoRecords="<tr><td colspan=2 align=""LEFT"" width=""100%"">Dancer not allocated to any act </td></tr>"
fp_sDataConn="s4d_2025"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="actname"
fp_sMenuValue="actname"
fp_sColTypes="&actname=202&eventname=202&filler=130&duplicates=202&lastupdated=135&datecreated=135&combined=11&background_link=201&sound_link=201&notes=203&music_on_entry=202&mixedage=130&mixed=11&act_duration=130&act_max_age=3&act_min_age=3&act_division=130&act_agegroup=130&act_nomination=202&comp_numbers=3&act_type=3&act_format=130&choreographer=202&teamname=202&studioID=3&eventID=3&act_ID=3&filler=130&session=20&actdancerID=130&declared=11&all_dancerID=3&all_act_ID=3&all_studioID=3&all_eventID=3&declare_ID=3&"
fp_iDisplayCols=2
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td style="border-left-style: none; border-left-width: medium; border-right-style: none; border-right-width: medium; border-top-style: none; border-top-width: medium; border-bottom-style: solid; border-bottom-width: 1px">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="actname,eventname,filler,duplicates,lastupdated,datecreated,combined,background_link,sound_link,notes,music_on_entry,mixedage,mixed,act_duration,act_max_age,act_min_age,act_division,act_agegroup,act_nomination,comp_numbers,act_type,act_format,choreographer,teamname,studioID,eventID,act_ID,filler,session,actdancerID,declared,all_dancerID,all_act_ID,all_studioID,all_eventID,declare_ID" s-column="actname" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;actname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"actname")%><!--webbot bot="DatabaseResultColumn" endspan --> 
			(<!--webbot bot="DatabaseResultColumn" s-columnnames="actname,eventname,filler,duplicates,lastupdated,datecreated,combined,background_link,sound_link,notes,music_on_entry,mixedage,mixed,act_duration,act_max_age,act_min_age,act_division,act_agegroup,act_nomination,comp_numbers,act_type,act_format,choreographer,teamname,studioID,eventID,act_ID,filler,session,actdancerID,declared,all_dancerID,all_act_ID,all_studioID,all_eventID,declare_ID" s-column="eventname" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eventname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"eventname")%><!--webbot bot="DatabaseResultColumn" endspan -->)</td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</div>

</body>
<script>
function focusToTop() {
    // Smoothly scroll to the top
    window.scrollTo({ top: -20, behavior: 'smooth' });

    // After scrolling, set focus to the top of the document
    // Timeout ensures focus happens after scroll animation
    setTimeout(() => {
        document.documentElement.setAttribute('tabindex', '-1'); // Make focusable
        document.documentElement.focus();
    }, 500); // Adjust delay if needed
}
window.onload=focusToTop();
</script>

<form method="POST">
	<p align="center">&nbsp;</p>
	<p align="center"><input type="button" class="button2" value="Close Window" name="B3" onclick="window.close()"></p>
</form>


</html>
