<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Europestage || we love dancing</title>
<meta name="viewport" content="width=100%, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.tutorialjinni.com/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
  <link rel="stylesheet" type="text/css" href="../registration/build/css/intlTelInput.css">
<script src="https://kit.fontawesome.com/e9d2b8eb05.js" crossorigin="anonymous"></script>

<script>setTimeout(function(){
   window.location.reload();
}, 180000);
</script>

<style type="text/css">

body {
  background-image: url("/images/black_red_bg.png");
  background-repeat: no-repeat;
  background-color: #FFFFFF;
  background-position: center;
  background-size: cover;
}
.div1 {
  width: 120px;
  height: 35px;
  display:table-cell;
  font-family: Bahnschrift; 
  font-size: 12pt; 
  border-radius:4px;
  border: 1px solid blue;
  background-color:#FFFFFF;
  text-align:left;
  vertical-align:middle;
}

input[type=submit] {
  width: 90px;
  height: 35px;
  background-color: #4CAF50;
  color: white;
  padding: 10px 10px;
  margin: 0px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

.div2 {
  width: 90%;
  height: 35px;
  padding: 10px;
  border-radius:12px;
  border: 1px #F0F0F0;
  background-color: #EAF4FF;

}
.button {
  border: none;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  background-color:#EAF4FF;
}
</style>

<body>

<div align="center">
	<table width="100%" border="1" bgcolor="#FFFFFF" style="font-family: Trebuchet MS; font-size: 10pt; border-collapse:collapse; border-left-width:2px; border-right-width:2px; border-top-width:2px" class="div2">
		<thead>
			<tr>
				<th ALIGN="LEFT" style="border-style: none; border-width: medium" colspan="8" valign="top">
				<p style="margin-top: 0; margin-bottom: 0">
				<img border="0" src="../../images/ES_60.png" width="78" 
    height="60">&nbsp;&nbsp; Europestage
				<span style="color: #202122; letter-spacing: normal; background-color: #FFFFFF">
				Riga</span> 28 February 2026&nbsp;&nbsp; 
			JUDGES' WORKING SHEETS</th>
			</tr>
			<tr>
				<th style="border-style: none; border-width: medium" width="3%">
				<p style="margin-top: 0; margin-bottom: 0"><b><font size="1">order</font></b></th>
				<th ALIGN="LEFT" style="border-style: none; border-width: medium" width="92%" colspan="4">
				<p style="margin-top: 0; margin-bottom: 0"><b><font size="1">studio</font></b></th>
				<th style="border-style: none; border-width: medium" width="5%" colspan="3">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<!--webbot bot="DatabaseRegionStart" 
   s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" 
   s-columntypes="3,3,3,200,202,202,202,202,202,130,202,130,130,130,3" 
   s-dataconnection="ontrack" b-tableformat="TRUE" 
   b-menuformat="FALSE" s-menuchoice="program_order" 
   s-menuvalue="program_order" b-tableborder="TRUE" 
   b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" 
   b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" 
   s-recordsource 
   s-displaycolumns="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" 
   s-criteria s-order 
   s-sql="SELECT act_ID, studioID, program_order, left(start_time,5) as start_time, studio, country_name, teamname, act_name, city, act_format, act_nomination, act_agegroup, es_actsTR.filler, mixedage , blockno from es_actsTR&lt;br&gt;LEFT JOIN es_studios on studio_ID=studioID&lt;br&gt;left join ontrack_countries on countriesID=countryID&lt;br&gt;where blockno=::blockno::&lt;br&gt;ORDER BY program_order ASC" 
   b-procedure="FALSE" clientside suggestedext="asp" 
   s-defaultfields="blockno=" s-norecordsfound="" 
   i-maxrecords="0" i-groupsize="0" botid="0" 
   u-dblib="../../../_fpclass/fpdblib.inc" 
   u-dbrgn1="../../../_fpclass/fpdbrgn1.inc" 
   u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" tag="TBODY" 
   preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" 
   b-UseDotNET="FALSE" CurrentExt sa-InputTypes 
   b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes 
   b-WasTableFormat="TRUE" b-ReplaceDatabaseRegion="FALSE" 
   startspan --><!--#include file="../../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT act_ID, studioID, program_order, left(start_time,5) as start_time, studio, country_name, teamname, act_name, city, act_format, act_nomination, act_agegroup, es_actsTR.filler, mixedage , blockno from es_actsTR LEFT JOIN es_studios on studio_ID=studioID left join ontrack_countries on countriesID=countryID where blockno=::blockno:: ORDER BY program_order ASC"
fp_sDefault="blockno="
fp_sNoRecords="<tr><td colspan=15 align=""LEFT"" width=""100%""></td></tr>"
fp_sDataConn="ontrack"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="program_order"
fp_sMenuValue="program_order"
fp_sColTypes="&act_ID=3&studioID=3&program_order=3&start_time=200&studio=202&country_name=202&teamname=202&act_name=202&city=202&act_format=130&act_nomination=202&act_agegroup=130&filler=130&mixedage=130&blockno=3&"
fp_iDisplayCols=15
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
				<td style="border-style: solid; border-width: 1px; " align="center" width="3%">
				<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="program_order" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;program_order&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"program_order")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></td>
				<td style="border-style: solid; border-width: 1px; " width="32%">
				<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="start_time" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;start_time&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"start_time")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></td>
				<td style="border-style: solid; border-width: 1px; " width="65%" align="left" colspan="6">
				<b>
				<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="studio" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;studio&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" s-ColumnTypes="3,3,3,202,202,202,130,202,130,3,3,202,11,203,3,3,202,3,3,17,17,135,130,11,135,202,130,3,202,202,202,202,202,202,3,202,202,202,3,135,135,202,202,11,3,202,203,202,203,130,3,202,130,130,202,202,130" startspan --><%=FP_FieldVal(fp_rs,"studio")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></b><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="city" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;city&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" s-ColumnTypes="3,200,202,202,202,202,202,202,130,202,130,130,130,11,202" startspan --><%=FP_FieldVal(fp_rs,"city")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="country_name" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;country_name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" s-ColumnTypes="3,3,3,202,202,202,130,202,130,3,3,202,11,203,3,3,202,3,3,17,17,135,130,11,135,202,130,3,202,202,202,202,202,202,3,202,202,202,3,135,135,202,202,11,3,202,203,202,203,130,3,202,130,130,202,202,130" startspan --><%=FP_FieldVal(fp_rs,"country_name")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></td>
			</tr>
			<tr>
				<td style="border-left-style:solid; border-left-width:1px; border-right-style:solid; border-right-width:1px; border-bottom-style:solid; border-bottom-width:1px" align="center" width="3%">
				&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="97%" colspan="7">
				<font color="#FF0000">
				<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="act_name" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_name")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></font><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="teamname" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;teamname&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan s-ColumnTypes="3,200,202,202,202,202,202,202,130,202,130,130,130,11,202,202,202,130,130,3,203,202,203,202,3,11,202,202,135,135,3,202,202,202,3,202,202,202,202,3,135,135,17,17,3,3,3,203,11,202,3,3,3,3,3" --><%=FP_FieldVal(fp_rs,"teamname")%><!--webbot 
    bot="DatabaseResultColumn" endspan --></td>
			</tr>
			<tr>
				<td style="border-style: solid; border-width: 1px; " align="center" width="3%" rowspan="2">&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="32%" rowspan="2">
				<p style="margin-top: 0; margin-bottom: 0">
				<!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="act_agegroup" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_agegroup&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_agegroup")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="mixedage" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;mixedage&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"mixedage")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="filler" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;filler&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"filler")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><!--webbot bot="DatabaseResultColumn" s-columnnames="act_ID,studioID,program_order,start_time,studio,country_name,teamname,act_name,city,act_format,act_nomination,act_agegroup,filler,mixedage,blockno" s-column="act_nomination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;act_nomination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"act_nomination")%><!--webbot 
    bot="DatabaseResultColumn" endspan --><p>&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="5%" align="center">
				<font size="1">Tech.</td></font>
				<td style="border-style: solid; border-width: 1px; " width="5%" align="center">
				<font size="1">Choreo.</font></td>
				<td style="border-style: solid; border-width: 1px; " width="5%" colspan="2" align="center">
				<font size="1">Present.</font></td>
				<td style="border-style: solid; border-width: 1px; " width="5%" align="center">
				<font size="1">Music.</font></td>
				<td style="border-style: solid; border-width: 1px; " width="45%" align="center">
				<span style="font-size: 9pt">Notes</span></td>
			</tr>
			<tr>
				<td style="border-style: solid; border-width: 1px; " width="5%" height="55">&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="5%" height="55">&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="5%" colspan="2" height="55">&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="5%" height="55">&nbsp;</td>
				<td style="border-style: solid; border-width: 1px; " width="45%" height="58">&nbsp;</td>
			</tr>
			<tr>
				<td style="border-style: solid; border-width: 1px; " align="center" width="100%" colspan="8">
				<hr size="1"></td>
			</tr>
			<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="../../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
	</table></div>

<script type="text/javascript">
function myfunc4()
{
var frm = document.getElementById("form4");frm.submit();
}
</script>

	</body>

</html>