vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|27 Feb 2026 14:59:45 -0000
vti_extenderversion:SR|6.0.2.8161
vti_author:SR|SAF-ACER\\safen
vti_modifiedby:SR|SAF-ACER\\safli
vti_timecreated:TR|05 Oct 2024 09:01:30 -0000
vti_title:SR|Europestage || we love dancing
vti_syncofs_2.59.119.221\:21:TW|27 Feb 2026 18:01:00 -0000
vti_syncwith_2.59.119.221\:21:TW|27 Feb 2026 14:59:45 -0000
vti_nexttolasttimemodified:TW|27 Feb 2026 14:48:09 -0000
vti_dataconns:VR|s4d_2025
vti_backlinkinfo:VX|
vti_cacheddtm:TX|27 Feb 2026 14:59:45 -0000
vti_filesize:IR|199422
vti_cachedtitle:SR|Europestage || we love dancing
vti_cachedbodystyle:SR|<body link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF">
vti_cachedlinkinfo:VX|S|https://kit.fontawesome.com/e9d2b8eb05.js Q|../myaccount/simple.css B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc B|../_fpclass/fpdblib.inc B|../_fpclass/fpdbrgn1.inc B|../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../global.asa B|../_fpclass/fpdbrgn2.inc
vti_cachedsvcrellinks:VX|NSSS|https://kit.fontawesome.com/e9d2b8eb05.js FQUS|myaccount/simple.css FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safli/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|true
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_cacheddataconns:VR|s4d_2025
vti_metatags:VR|HTTP-EQUIV=content-type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0,\\ maximum-scale=1.0
vti_charset:SR|utf-8
