vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|10 Oct 2025 17:50:35 -0000
vti_extenderversion:SR|6.0.2.8161
vti_author:SR|SAF-ACER\\safen
vti_modifiedby:SR|SAF-ACER\\safen
vti_timecreated:TR|05 Oct 2024 09:01:30 -0000
vti_title:SR|space4dance
vti_syncofs_2.59.119.221\:21:TW|10 Oct 2025 19:50:00 -0000
vti_syncwith_2.59.119.221\:21:TW|10 Oct 2025 17:50:35 -0000
vti_nexttolasttimemodified:TW|10 Oct 2025 17:15:26 -0000
vti_backlinkinfo:VX|myaccount/studios/default_copy(3).asp myaccount/studios/studiomenu.asp
vti_dataconns:VR|s4d_2025
vti_cacheddtm:TX|10 Oct 2025 17:50:35 -0000
vti_filesize:IR|63328
vti_cachedtitle:SR|space4dance
vti_cachedbodystyle:SR|<body bgcolor="#000000">
vti_cachedlinkinfo:VX|H|../favicon.ico S|https://kit.fontawesome.com/e9d2b8eb05.js Q|../simple.css B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa A|../acts/waiting.asp B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa A|../acts/review_places.asp B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa A|../acts/reserve_places_TR.asp B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa A|../acts/reserve_places_WOD.asp B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa A|../dancers/dancer_upload.asp B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa B|../../_fpclass/fpdbrgn2.inc B|../../_fpclass/fpdblib.inc B|../../_fpclass/fpdbrgn1.inc B|../../_fpclass/fpdbrgn2.inc D|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 H|../../global.asa A|../acts/acts_new.asp B|../../_fpclass/fpdbrgn2.inc
vti_cachedsvcrellinks:VX|FHUS|myaccount/favicon.ico NSSS|https://kit.fontawesome.com/e9d2b8eb05.js FQUS|myaccount/simple.css FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FAUS|myaccount/acts/waiting.asp FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FAUS|myaccount/acts/review_places.asp FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FAUS|myaccount/acts/reserve_places_TR.asp FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FAUS|myaccount/acts/reserve_places_WOD.asp FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FAUS|myaccount/dancers/dancer_upload.asp FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FBUS|_fpclass/fpdbrgn2.inc FBUS|_fpclass/fpdblib.inc FBUS|_fpclass/fpdbrgn1.inc FBUS|_fpclass/fpdbrgn2.inc NDUS|X-DATACONN:///C:/Users/safen/Dropbox\\ (Personal)/space4dance.org/s4d_2025 FHUS|global.asa FAUS|myaccount/acts/acts_new.asp FBUS|_fpclass/fpdbrgn2.inc
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|true
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_cacheddataconns:VR|s4d_2025
vti_metatags:VR|HTTP-EQUIV=content-type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0,\\ maximum-scale=1.0 HTTP-EQUIV=X-UA-Compatible IE=edge
vti_charset:SR|utf-8
